# Generated by Django 4.2.16 on 2024-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_media_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='task-media/'),
        ),
    ]
